export const STOCKS = {
  LargeCap: [
    // Nifty 50
    "RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS","SBIN.NS",
    "LT.NS","HINDUNILVR.NS","ITC.NS","KOTAKBANK.NS","AXISBANK.NS","BAJFINANCE.NS",
    "ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS","TITAN.NS","ULTRACEMCO.NS",
    "NESTLEIND.NS","WIPRO.NS",
    "ADANIENT.NS","ADANIPORTS.NS","COALINDIA.NS","JSWSTEEL.NS","TATASTEEL.NS",
    "INDUSINDBK.NS","BAJAJFINSV.NS","HCLTECH.NS","DRREDDY.NS","CIPLA.NS",
    "DIVISLAB.NS","BRITANNIA.NS","EICHERMOT.NS","HEROMOTOCO.NS",
    "SHREECEM.NS","UPL.NS","TECHM.NS","TATACONSUM.NS",
    "APOLLOHOSP.NS","ADANIGREEN.NS","ADANITRANS.NS","ADANIPOWER.NS"
  ],

  MidCap: [
    // Nifty Next 50 + Midcap leaders
    "PIDILITIND.NS","DMART.NS","SIEMENS.NS","ABB.NS","HAVELLS.NS","DABUR.NS",
    "BANKBARODA.NS","PNB.NS","ICICIPRULI.NS","ICICIGI.NS","SBILIFE.NS",
    "HDFCLIFE.NS","INDIGO.NS","NAUKRI.NS","COLPAL.NS","GODREJCP.NS",
    "MCDOWELL-N.NS","VEDL.NS","AMBUJACEM.NS","ACC.NS","SAIL.NS",
    "JUBLFOOD.NS","BERGEPAINT.NS","TRENT.NS","MPHASIS.NS","LTIM.NS",
    "COFORGE.NS","PERSISTENT.NS","TATAELXSI.NS","KPITTECH.NS","LUPIN.NS",
    "AUROPHARMA.NS","ZYDUSLIFE.NS","TORNTPHARM.NS","ALKEM.NS",
    "BALKRISIND.NS","ASHOKLEY.NS","BHARATFORG.NS","ESCORTS.NS",
    "SRF.NS","PIIND.NS","DIXON.NS","INDIAMART.NS","PAGEIND.NS",
    "MUTHOOTFIN.NS","CHOLAFIN.NS","LICHSGFIN.NS",
    "FEDERALBNK.NS","IDFCFIRSTB.NS","BANDHANBNK.NS"
  ],

  SmallCap: [
    // keep limited for performance
    "IRCTC.NS","CDSL.NS","BSE.NS","MCX.NS",
    "CLEAN.NS","ROUTE.NS","HAPPSTMNDS.NS","TANLA.NS",
    "EASEMYTRIP.NS","NAZARA.NS"
  ]
};